	Spp    = myData[i,1]
	ScName = myData[i,2]
	Area   = myData[i,3]
	Linf   = myData[i,4]
	K      = myData[i,5]
	t0     = myData[i,6]
	tr     = myData[i,7] 
	Amax   = myData[i,8]
	M      = myData[i,9]
	arlp   = myData[i,10]
	brlp   = myData[i,11]
	amat   = myData[i,12]
	bmat   = myData[i,13]
	l50    = myData[i,14]
	l95    = myData[i,15]
	Tspw   = myData[i,16]
    age <- seq(tr,Amax,1)
    L   <- vbgFUN(Linf,K,t0,age)
    W   <- arlp*L^(brlp)
    Ph  <- matFUN(amat,bmat,L)
    Sel <- selFUN(l50,l95,L)
    S0 <- SPRFmort(0,Amax,Tspw)$SPRo
    out1 <- GetAlphaBeta(S0,SRModel,h,R0,Gamma)
    alpha <- out1$Alpha
    beta <- out1$Beta